# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('version', models.FloatField()),
                ('deployed_t', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
