# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170418_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name_plural': 'Ports'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name_plural': 'Stacks'},
        ),
        migrations.RenameField(
            model_name='port',
            old_name='service',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='stack',
            new_name='level',
        ),
    ]
