# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variable_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='level',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='level',
            new_name='stack',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='level',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='level',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='stack',
            name='version',
            field=models.CharField(default='3', max_length=8),
        ),
    ]
