# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170419_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ('created_t',), 'verbose_name_plural': 'Stacks'},
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default='False', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.CharField(max_length=256, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='version',
            field=models.CharField(choices=[('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2')], default='3.0', max_length=8),
        ),
    ]
