# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170422_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_version',
            field=models.CharField(default='latest', max_length=64, verbose_name='v.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.BooleanField(default='False', help_text='Is active', verbose_name='Status'),
        ),
    ]
