# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170425_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DEV', 'DEV'), ('INT', 'INT'), ('PPE', 'PPE')], default='DEV', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('created_t', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='replicas',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Replicas'),
        ),
        migrations.AddField(
            model_name='service',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Environment'),
        ),
        migrations.AddField(
            model_name='stack',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='api.Environment'),
        ),
    ]
