# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170512_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='port_range',
            field=models.CharField(default='8000-9000', help_text='Alowed range 88-190,1,3,300-350', max_length=256, validators=[django.core.validators.RegexValidator('^(\\d+[-,]*\\d+)+$', message='Use syntax 88-190,1,2,3,300-350')], verbose_name='Ports range'),
        ),
    ]
