# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_auto_20170512_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_t', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='api.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_t', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='ui.Application')),
            ],
        ),
    ]
