# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.CharField(blank=True, choices=[('xms', 'xms'), ('sms', 'sms'), ('ws', 'ws'), ('farm', 'farm'), ('cube', 'active-pivot'), ('cube', 'active-pivot'), ('svc', 'service'), ('elk', 'elk')], default='svc', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='applicationurl',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='api.Service'),
        ),
    ]
